version: '2'
services:
  api:
    build: .
    ports:
      - "8888:8888"
    links:
      - db
    environment:
      - NODE_ENV=development
      - PORT_NUM=8888
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
    command: npm start
  db:
    build: database/
